### ISSUE TITLE
Add prefetch to AsyncSegmentReader (via wrapper)

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega-client-rust#180]
**Problem description**
Instead of #153 which does not affect events we should take advantage of the fact that in `AsyncSegmentReader` reads are highly predictable. 

**Problem location**
In AsyncSegmentReader::read each time the call is made a new request it issued to the controller to locate the endpoint, and then upon completion it returns just the data that was requested. This results in two round trip latencies on call paths that are perceptible to the end user.

**Suggestions for an improvement**
We should create a PrefetchingAsyncSegmentReader which wraps AsyncSegmentReader. This will issue larger read calls than the caller requested and hold onto the data locally. If the next call is for the following offset it can simply be returned without having to fetch more data. (Or wait on the future of the already issued request) We don't have to worry about boundaries because it is valid to return less data than the caller asked for.

Additionally AsyncSegmentReader should be modified to be optimistic and assume that the endpoint has not changed on the first attempt and only fetch the new endpoint when an error is encountered.

**Comment by Tristan1900** [comment]
The prefetching looks good for improving read latency, however, the two round trip part is not exactly true. The `AsyncSegmentReader` caches an endpoint. Only when `AsyncSegmentReader` is created or the read result returns a retryable error that it will call controller to update the endpoint, otherwise it's just using the cached endpoint.
