### ISSUE TITLE
Excessive connections to Segment Store

### ISSUE THREAD

**Issue by claudiofahey** [pravega/pravega-client-rust#223]
**Problem description**
I have observed 1000+ TCP connections from a Rust application to the Segment Store of a standalone Pravega instance. At this point, the application no longer accepts new connections or can open new files because the OS does not allow any more open files.

The application that reproduces the problem is an HTTP server that provides HTTP Live Streaming from a Pravega stream. It is a Rust application built on Hyper/Warp. Web browsers using it will initiate requests to read bytes from a Pravega byte stream and then cancel the request. This may be contributing to this problem. It is not clear to me if the application code is leaking the connection or if it is the Pravega client. There is a single instance of the Pravega client factory which is created when the application starts.

https://github.com/pravega/gstreamer-pravega/blob/db74586a627f1f65f26412b979fde18916f32f1b/pravega-video-server/src/main.rs#L220

**Problem location**
Possibly related to connection pooling.

**Suggestions for an improvement**
Unknown.

**Comment by tkaitchuck** [comment]
Connections should be returned to the pool and reused when they are dropped. The most likely explanation is they simply aren't being dropped.
The easiest way to determine which code is at fault would be to add logging to the the drop at various levels of abstraction and it should be possible to locate the 'level' of the leak.

**Comment by Tristan1900** [comment]
I tried locally and find one possible scenario. 
It could be at this [line](https://github.com/pravega/pravega-client-rust/blob/master/src/segment_reader.rs#L470). If user call `seekEnd(0)` repeatedly but there is no data in the stream, then that line of code will wait for a long time until timeout(default 3600s) or something returns and then it will proceed to the next line to quit the method and return the connection back to the pool. Currently I don't have a good solution to fix this other than reducing the request timeout so that line of code can return faster. 
@claudiofahey Is it a valid assumption that `seekEnd(0)` is called repeatedly but nothing is in the stream?
Thanks!

**Comment by claudiofahey** [comment]
Yes that is a valid assumption. The application is calling `seek(SeekFrom::End(-20))` about once a second [here](https://github.com/pravega/gstreamer-pravega/blob/db74586a627f1f65f26412b979fde18916f32f1b/pravega-video/src/index.rs#L169). Normally there are new events but if the writing process stops, then there will be no new events.
