### ISSUE TITLE
Python client should support Python 3.6.9

### ISSUE THREAD

**Issue by claudiofahey** [pravega/pravega-client-rust#320]
**Problem description**
Python 3.6.9 is standard with Ubuntu 18.04.5 LTS but the Pravega Python client does not support it, as it only supports Python 3.9.

**Problem location**
Pravega Python client.

**Suggestions for an improvement**
Python client should support Python 3.6.9

**Comment by shrids** [comment]
The current Pravega python client does not support 3.6.9 version of python because it relies on https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_running_loop to create a Python future object. 
This function is enabled from python 3.7 onwards.

The current Python pravega client supports version 3.8, 3.9 . This can be easily extended to support Python 3.7. 
(Ubuntu 20.04.2 LTS by default has 3.8.2 version of python.).

Next Steps: 
There is an enhancement request #306 to use pyo3-asyncio crate instead of managing the Python futures. As I understand this approach should eliminate this dependency on a Python3.7+ version of the API and enable 3.6.9 support.
